name: SDCNN
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # project-specific packages
  - numpy
  - pandas
  - scikit-image
  - joblib
  - tqdm
  - scikit-learn
  - pytorch==1.11.0
  - torchvision==0.12.0
  - pip
  - python=3.8
  - matplotlib