name: SDCNN
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # project-specific packages
  - numpy
  - pandas
  - scikit-image
  - joblib
  - tqdm
  - scikit-learn
  - pytorch==1.11.0
  - torchvision==0.12.0
  - python=3.8
  - matplotlib
  - plotly 
  - plotly-orca
  - pip
  - pip:                # everything under this, installed by pip
    - thop
    - lightly

